[MIRROR] [MDB IGNORE] Kapulimbs
JollyStation/JollyStation pull request #85
Opened 2022-04-02 01:08 UTC by JollyStationBot

Original PR: https://github.com/tgstation/tgstation/pull/65523
-----

## About The Pull Request
Ports Kapulimbs 1.0 & 1.1 from Shiptest, while trimming some unrelated code.

- https://github.com/shiptest-ss13/Shiptest/pull/530
- https://github.com/shiptest-ss13/Shiptest/pull/726

Kapulimbs is a bodypart & update icons rewrite I created with a few specific intentions:

1. Simplify the code
2. Allow players to create frankensteins of different species parts
3. Enable non-humanoid species to be created

### How is this achieved?
Bodyparts are now pathed to their specific species, and they can have their own unique life loops, appearances, and anything else a bodypart child should have. A "bodytypes" bitfield is utilized to differentiate important attributes, such as BODYTYPE_ORGANIC and BODYTYPE_HUMANOID.

## Why It's Good For The Game
Better code AND better fun.
![image](https://user-images.githubusercontent.com/75460809/158751444-6e05d685-9778-4429-9629-4b042e76363e.png)

## Changelog

:cl:
add: Limbgrower limbs are now a sickly green
refactor: Digitigrade legs should now behave consistently.
refactor: Limbs will no longer update appearance as owner is transferred, allowing for multi-species frankensteins
fix: CHANGELING TRANSFORM FUNCTIONS PROPERLY
del: Synths and synth-related mechanics (Synth fugative)
/:cl:

2022-04-02 03:10 UTC, Jolly-66 commented
I take a look at GitHub

Ugh

2022-04-03 05:03 UTC, Kapu1178 requested changes

2022-04-03 05:03 UTC, Kapu1178 commented on jollystation_modules/code/modules/mob/living/carbon/human/species_types/skrell.dm
> +	if(our_head?.bodytype == BODYTYPE_ROBOTIC)
this is a bitflag not a single value.

`if(ourhead && !IS_ORGANIC_LIMB(ourhead)`

2022-04-03 16:33 UTC, Jolly-66 commented
@prodirus 
Can you update our modular one with whatever you changed 

Thx bby

2022-04-03 23:22 UTC, Jolly-66 commented
@prodirus 
Skrell organs are broken but thats for another time

Everything works boys lets pack 'er up.

2022-04-03 23:22 UTC, merged